server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order-service
          uri : "lb://order-service"
          predicates:
            - Path=/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/